apiVersion: batch/v1
kind: Job
metadata:
  name: java-job-lukin-$BUILD_NUMBER
spec:
  template:
    spec:
      containers:
      - name: $JOB_NAME
        image: mrlvs/java:1.0.0
      restartPolicy: Never
