apiVersion: batch/v1
kind: Job
metadata:
  name: java-job
spec:
  template:
    spec:
      containers:
      - name: $JOB_NAME-$GIT_AUTHOR_NAME
        image: mrlvs/java:1.0.0
      restartPolicy: Never
