pipeline {
    agent {
        label 'docker'
    }

    environment {
        IMAGE_REPO = 'mrlvs/java'
        TAG = "1.0.1"
    }

    stages {
        stage("Build") {
            steps {
                sh '''
                printenv
                pwd
                ls -la
                cd /hw2
                docker pull $IMAGE_REPO:$TAG
                pwd
                ls -la
                docker build -t $IMAGE_REPO:$JOB_NAME-$BUILD_NUMBER ./
                '''

               
            }
        }
    }
       
}