apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "hell-m-chart.fullname" .}}"
spec:
  template:
    spec:
      containers:
      - name: "{{ include "hell-m-chart.fullname" .}}"
        image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
      restartPolicy: Never
